project_id = "omyrlnrqvfofijxwozop"

[functions.check-feature-access]
verify_jwt = false

[functions.usaspending-search]
verify_jwt = false

[functions.sam-search]
verify_jwt = false

[functions.parse-search-query]
verify_jwt = false

[functions.sam-search]
verify_jwt = false

[functions.ai-generate-proposal]
verify_jwt = true

[functions.ai-opportunity-chat]
verify_jwt = false
