project_id = "omyrlnrqvfofijxwozop"

[functions.check-feature-access]
verify_jwt = false

[functions.usaspending-search]
verify_jwt = false

[functions.sam-search]
verify_jwt = false

[functions.parse-search-query]
verify_jwt = false

[functions.ai-generate-proposal]
verify_jwt = false

[functions.ai-opportunity-chat]
verify_jwt = false

[functions.ai-contract-score]
verify_jwt = false

[functions.ai-recommend-contracts]
verify_jwt = false

[functions.ai-profile-optimizer]
verify_jwt = false

[functions.ai-document-summary]
verify_jwt = false

[functions.sam-refresh-single]
verify_jwt = false

[functions.ai-contract-summary]
verify_jwt = false
